version: "3.9"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "name"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./mireatom-backend
    command: sh -c "python mireatom-backend/mireatom/manage.py migrate && 
                    python mireatom-backend/mireatom/manage.py populate_db && 
                    python mireatom-backend/mireatom/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./mireatom-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: